INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.39', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.39.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.30', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.30.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.29', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.29.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.16', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.16.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.20', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.20.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.18', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.18.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.27', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.27.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.39', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.40.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.85', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.56.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.31', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.31.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.10', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.10.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.36', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.46.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.35', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.48.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.5', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.05.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.50', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.61.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.55', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.81.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.22', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.22.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.47', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.58.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.8', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.08.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.37', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.44.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.53', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.78.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.43', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.64.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.9', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.09.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.84', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.55.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19.80', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.50.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H19', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.00.H19';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'K19', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.00.K19';


