INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.13', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.13.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.21', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.21.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.23', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.23.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.00.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.22', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.22.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.39', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.39.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.55', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.55.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.17', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.17.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.17.01', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.01.17.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15.01', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '001.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15.04', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '004.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.04', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '004.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.06', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '006.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.01', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '001.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.06', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '006.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.05', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '005.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.03', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '003.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.01', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '001.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15.05', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '005.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15.06', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '006.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.07', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '007.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.05', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '005.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.03', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '003.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.02', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '002.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.04', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '004.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.07', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '007.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.06', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '006.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.02', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '002.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.05', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '005.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15.02', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '002.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.08', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '008.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.18', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.18.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.21', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.21.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.19', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.19.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.01', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '001.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.20', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.20.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.04', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '004.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.56', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.56.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.45', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.45.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.58', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.58.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.50', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.50.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.44', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.44.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.41', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.41.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.27', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.27.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.26', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.26.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.11', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.11.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.55', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.55.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.17', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.17.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.17.01', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.01.17.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15.01', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '001.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15.04', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '004.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.04', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '004.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.06', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '006.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.01', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '001.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.06', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '006.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.05', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '005.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.03', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '003.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.05', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '005.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15.05', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '005.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.07', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '007.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15.06', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '006.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.03', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '003.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.02', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '002.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.04', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '004.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.07', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '007.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.06', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '006.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.01', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '001.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.19', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.19.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.18', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.18.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.02', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '002.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.20', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.20.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16.05', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '005.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.21', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.21.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.01', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '001.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15.02', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '002.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13.08', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '008.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14.04', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '004.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.56', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.56.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.45', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.45.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.58', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.58.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.50', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.50.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.44', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.44.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.41', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.41.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.27', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.27.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.16', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.16.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.13', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.13.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.14', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.14.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.11', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.11.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.26', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.26.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15.15', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.15.15.G04';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G04.15', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.15.G04';

