
INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.06', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.06.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.07', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.07.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H13.46', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.07.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.22', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.22.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.19', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.19.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.27', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.28.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.10', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.10.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.20', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.20.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.04', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.04.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.14', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.14.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.11', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.11.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.09', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.09.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.03', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.03.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.29', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.30.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.21', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.21.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.00.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.02', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.02.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.25', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.25.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.12', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.12.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.13', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.13.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.28', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.29.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.18', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.18.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.08', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.08.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.05', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.05.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.15', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.15.G16';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.12.31', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.31.12.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.12.28', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.28.12.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.12.34', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.34.12.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.34.33', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.27.34.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.10.50', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.30.10.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.12.29', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.29.12.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.12.30', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.30.12.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.12.35', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.35.12.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'G16.14.03', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.71.35.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.12.37', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.37.12.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.7.28', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.27.07.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.34.32', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.26.34.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.12.32', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.32.12.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.12.38', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.38.12.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.17.50', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.28.17.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.12.36', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.36.12.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08.10.24', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.24.10.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'K08', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.00.K08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H08', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.00.H08';

INSERT INTO EDOC_DM_DONVI 
  (MA_DON_VI, TEN_DON_VI, MA_LOAI_DON_VI, MA_DON_VI_CHU_QUAN, MA_DINH_DANH, MA_TINH, TRANG_THAI, DIA_CHI, DIEN_THOAI, FAX, EMAIL, WEBSITE, CAP_DON_VI, DINH_DANH_SORT, LOAI_LIEN_THONG, MA_TK_LIEN_THONG, MA_DON_VI_VPCP, MA_DON_VI_CHA_VPCP, NGAY_DONG_BO, MA_DINH_DANH_CU, HAN_MUC_DUNG_LUONG) 
SELECT 
  (select max(MA_DON_VI) + 1  from EDOC_DM_DONVI), 
  dv.    TEN_DON_VI, 
  dv.MA_LOAI_DON_VI, dv.MA_DON_VI_CHU_QUAN, 'H07', dv.MA_TINH, dv.TRANG_THAI, dv.DIA_CHI, dv.DIEN_THOAI, dv.FAX, dv.EMAIL, dv.WEBSITE, dv.CAP_DON_VI, dv.DINH_DANH_SORT, dv.LOAI_LIEN_THONG, dv.MA_TK_LIEN_THONG, dv.MA_DON_VI_VPCP, dv.MA_DON_VI_CHA_VPCP, SYSDATE, dv.MA_DINH_DANH, dv.HAN_MUC_DUNG_LUONG 
FROM EDOC_DM_DONVI dv 
WHERE dv.MA_DINH_DANH = '000.00.00.H07';

